<?php

return [

    'kecamatan' => [
        'Banjarnegara',
        'Banjarmangu',
        'Batur',
        'Bawang',
        'Kalibening',
        'Karangkobar',
        'Madukara',
        'Mandiraja',
        'Pagedongan',
        'Pagentan',
        'Pandanarum',
        'Pejawaran',
        'Punggelan',
        'Purwanegara',
        'Purwareja Klampok',
        'Rakit',
        'Sigaluh',
        'Susukan',
        'Wanadadi',
        'Wanayasa',
    ],

    // Desa/Kelurahan per kecamatan (gabung jadi satu daftar "Desa/Kelurahan")
    // Sumber nama desa & kelurahan: Wikipedia (halaman daftar desa per kecamatan). :contentReference[oaicite:1]{index=1}
    'desa_by_kecamatan' => [

        'Banjarmangu' => [
            'Banjarkulon',
            'Banjarmangu',
            'Beji',
            'Gripit',
            'Jenggawur',
            'Kalilunjar',
            'Kendaga',
            'Kesenet',
            'Majatengah',
            'Paseh',
            'Pekandangan',
            'Prendengan',
            'Rejasari',
            'Sigeblok',
            'Sijenggung',
            'Sijeruk',
            'Sipedang',
        ],

        'Banjarnegara' => [
            // Desa:
            'Ampelsari',
            'Cendana',
            'Sokayasa',
            'Tlagawera',
            // Kelurahan:
            'Argasoka',
            'Karangtengah',
            'Krandegan',
            'Kutabanjarnegara',
            'Parakancanggah',
            'Semampir',
            'Semarang',
            'Sokanandi',
            'Wangon',
        ],

        'Batur' => [
            'Bakal',
            'Batur',
            'Dieng Kulon',
            'Karangtengah',
            'Kepakisan',
            'Pasurenan',
            'Pekasiran',
            'Sumberejo',
        ],

        'Bawang' => [
            'Bandingan',
            'Bawang',
            'Binorong',
            'Blambangan',
            'Depok',
            'Gemuruh',
            'Joho',
            'Kebondalem',
            'Kutayasa',
            'Majalengka',
            'Mantrianom',
            'Masaran',
            'Pucang',
            'Serang',
            'Wanadri',
            'Watuurip',
            'Winong',
            'Wiramastra',
        ],

        'Kalibening' => [
            'Asinan',
            'Bedana',
            'Gununglangit',
            'Kalibening',
            'Kalibombong',
            'Kalisat Kidul',
            'Karang Anyar',
            'Kasinoman',
            'Kertasari',
            'Majatengah',
            'Plorengan',
            'Sembawa',
            'Sidakangen',
            'Sikumpul',
            'Sirukem',
            'Sirukun',
        ],

        'Karangkobar' => [
            'Ambal',
            'Binangun',
            'Gumelar',
            'Jlegong',
            'Karanggondang',
            'Krangkobar',
            'Leksana',
            'Pagerpelah',
            'Pasuruhan',
            'Paweden',
            'Purwodadi',
            'Sampang',
            'Slatri',
        ],

        'Madukara' => [
            // Desa:
            'Bantarwaru',
            'Blitar',
            'Clapar',
            'Dawuhan',
            'Gununggiana',
            'Kaliurip',
            'Karanganyar',
            'Kutayasa',
            'Limbangan',
            'Madukara',
            'Pagelak',
            'Pakelen',
            'Pekauman',
            'Penawangan',
            'Petambakan',
            'Rakitan',
            'Sered',
            'Talunamba',
            // Kelurahan:
            'Kenteng',
            'Rejasa',
        ],

        'Mandiraja' => [
            'Banjengan',
            'Blimbing',
            'Candiwulan',
            'Glempang',
            'Jalatunda',
            'Kaliwungu',
            'Kebakalan',
            'Kebanaran',
            'Kertayasa',
            'Mandirajakulon',
            'Mandirajawetan',
            'Panggisari',
            'Purwasaba',
            'Salamerta',
            'Simbang',
            'Somawangi',
        ],

        'Pagedongan' => [
            'Duren',
            'Gentansari',
            'Gunungjati',
            'Kebutuhduwur',
            'Kebutuhjurang',
            'Lebakwangi',
            'Pagedongan',
            'Pesangkalan',
            'Twelagiri',
        ],

        'Pagentan' => [
            'Aribaya',
            'Babadan',
            'Gumingsir',
            'Kalitlaga',
            'Karangnangka',
            'Karekan',
            'Kasmaran',
            'Kayuares',
            'Larangan',
            'Majasari',
            'Metawana',
            'Nagasari',
            'Pagentan',
            'Plumbungan',
            'Sokaraja',
            'Tegaljeruk',
        ],

        'Pandanarum' => [
            'Beji',
            'Lawen',
            'Pandanarum',
            'Pasegeran',
            'Pingit Lor',
            'Pringamba',
            'Sinduaji',
            'Sirongge',
        ],

        'Pejawaran' => [
            'Beji',
            'Biting',
            'Condong Campur',
            'Darmayasa',
            'Gembol',
            'Giritirta',
            'Grogol',
            'Kalilunjar',
            'Karangsari',
            'Panusupan',
            'Pegundungan',
            'Pejawaran',
            'Ratamba',
            'Sarwodadi',
            'Semangkung',
            'Sidengok',
            'Tlahap',
        ],

        'Punggelan' => [
            'Badakarya',
            'Bondolharjo',
            'Danakerta',
            'Jembangan',
            'Karangsari',
            'Kecepit',
            'Klapa',
            'Mlaya',
            'Petuguran',
            'Punggelan',
            'Purwasana',
            'Sambong',
            'Sawangan',
            'Sidarata',
            'Tanjungtirta',
            'Tlaga',
            'Tribuana',
        ],

        'Purwanegara' => [
            'Danaraja',
            'Gumiwang',
            'Kaliajir',
            'Kalipelus',
            'Kalitengah',
            'Karanganyar',
            'Kutawuluh',
            'Merden',
            'Mertasari',
            'Parakan',
            'Petir',
            'Pucungbedug',
            'Purwonegoro',
        ],

        'Purwareja Klampok' => [
            'Kalilandak',
            'Kalimandi',
            'Kaliwinasuh',
            'Kecitran',
            'Klampok',
            'Pagak',
            'Purworejo',
            'Sirkandi',
        ],

        'Rakit' => [
            'Adipasir',
            'Badamita',
            'Bandingan',
            'Gelang',
            'Kincang',
            'Lengkong',
            'Luwung',
            'Pingit',
            'Rakit',
            'Situwangi',
            'Tanjunganom',
        ],

        'Sigaluh' => [
            // Desa:
            'Bandingan',
            'Bojanegara',
            'Gembongan',
            'Karangmangu',
            'Kemiri',
            'Panawaren',
            'Prigi',
            'Pringamba',
            'Randegan',
            'Sawal',
            'Sigaluh',
            'Singomerto',
            'Tunggara',
            'Wanacipta',
            // Kelurahan:
            'Kalibenda',
        ],

        'Susukan' => [
            'Berta',
            'Brengkok',
            'Derik',
            'Dermasari',
            'Gumelem Kulon',
            'Gumelem Wetan',
            'Karangjati',
            'Karangsalam',
            'Kedawung',
            'Kemranggon',
            'Pakikiran',
            'Panerusan Kulon',
            'Panerusan Wetan',
            'Piasa Wetan',
            'Susukan',
        ],

        'Wanadadi' => [
            'Gumingsir',
            'Kandangwangi',
            'Karangjambe',
            'Karangkemiri',
            'Kasalib',
            'Lemahjaya',
            'Linggasari',
            'Medayu',
            'Tapen',
            'Wanadadi',
            'Wanakarsa',
        ],

        'Wanayasa' => [
            'Balun',
            'Bantar',
            'Dawuhan',
            'Jatilawang',
            'Karangtengah',
            'Kasimpar',
            'Kubang',
            'Legoksayem',
            'Pagergunung',
            'Pandansari',
            'Penanggungan',
            'Kalideres',
            'Susukan',
            'Suwidak',
            'Tempuran',
            'Wanaraja',
            'Wanayasa',
        ],
    ],
];
